name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: '选择要构建的分支'
        required: true
        default: 'main'
        type: string

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}
        fetch-depth: 0 

    - name: Set up MinGW-w64 (g++)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: mingw-w64-x86_64-gcc

    - name: Generate Version and Release Tag
      id: meta
      shell: bash
      run: |
        BUILD_TIME=$(date +'%Y%m%d-%H%M%S')
        SHORT_SHA=$(git rev-parse --short HEAD)
        TAG_NAME="${BUILD_TIME}-${SHORT_SHA}"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
        PREV_SHA=$(git rev-list --tags --max-count=1 2>/dev/null || git rev-list --max-parents=0 HEAD | head -n 1)
        echo "PREV_SHA=${PREV_SHA}" >> $GITHUB_ENV

    - name: Build with g++
      shell: msys2 {0}
      run: |
        mkdir -p build
        g++ -std=c++17 -O2 -Wall -static -Ithird_party -o build/tuftools.exe src/*.cpp -lwinhttp

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.meta.outputs.tag }}
        name: ci-${{ steps.meta.outputs.tag }}
        body: |
          build with g++ (MinGW-w64)
        files: |
          build/tuftools.exe
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
